Updated the color palette for the custom lightTheme
transformerjnm/facebook-clone pull request #27
Opened 2021-01-05 13:41 UTC by ChadAltenberger

Added colors to our custom MUI lightTheme in 'theme.js'. _Primary_, _secondary_, _info_, _error_, and _success_

Accessed as... _lightTheme.palette.primary.main_

_Primary_ contains 3 values: _light_, _main_ and _dark_. _Light_ will be the white color, and _main_ and _dark_ will be the two shades of grey

_Secondary_ just has one main value and will be the blue color

_Info_ has just one main value and will be the dark grey/black color(text input, user names, etc)

_Error_ has just one main value and will be the red color

_Success_ has just one main value and will be the green color

2021-01-05 15:36 UTC, transformerjnm commented
Although it wont let me add a review, the code looks good!

2021-01-05 17:40 UTC, Blaine137 requested changes
Everything looks good, however, I personally think you should hard code the light and dark colors for secondary. Since you did not provide values for those two properties, light and dark are calculated based off the main color.

2021-01-05 19:10 UTC, ChadAltenberger commented
> Everything looks good, however, I personally think you should hard code the light and dark colors for secondary. Since you did not provide values for those two properties, light and dark are calculated based off the main color.

I can do that. Although, I didn't really see any other shades of the blue. Did you have something in mind? You want something lighter and darker than what MUI calculates? Thanks.

2021-01-06 23:51 UTC, transformerjnm commented
Why did we remove the hover effect on all IconButton for the application?

2021-01-07 01:09 UTC, ChadAltenberger commented
> Why did we remove the hover effect on all IconButton for the application?

If we're trying to match the styling on Facebook's page, the default hover effect for MUI's IconButton won't match it for the majority of elements with a hover effect. I'm not sure if there's a better work-around but am open to your thoughts.

2021-01-07 14:38 UTC, Blaine137 approved these changes
The changes look good Chad! Thank you!

2021-01-07 15:42 UTC, merged